### ISSUE TITLE
How do I disable Algolia in test env?

### ISSUE THREAD

**Issue by demagu** [algolia/search-bundle#122]
Tried conditionally register AlgoliaBundle in my `AppKernel` (so it's available only in `prod` and `dev` environments) but then my tests fail due to non-existent services like `"algolia.indexer"`...

Doesn't seem I can disable Doctrine's listeners in `config_test.yml` just for AlgoliaBundle. Can I?

**Comment by julienbourdeau** [comment]
As of today there is no easy way to do it. I think a good way would be to create some kind of mock.

I'm thinking of the `NullEngine` of Laravel Scout for instance. With Scout you can easily replace the AlgoliaEngine by this one, then no operation is ever performed.

We could have a class that behave like the indexer, with the right method but doesn't do anything.
If you manage to do it, it would be great if you could open a Pull Request 🙌

**Comment by demagu** [comment]
Thanks for the input @julienbourdeau 

What would be the benefit of doing it this way versus just adding ability to disable listeners per environment (in config files)?

Since bundle is already depending on Doctrine's `onFlush` and `postFlush` events adding configuration options like:

```yaml
# in config_test.yml

algolia:
       listener:
              insert: false
              update: false
              delete: false
```
```yaml
# in config.yml

algolia:
       listener:
              insert: true # default - so it can be skipped in config for easy configuration and BC compat
              update: true
              delete: true
```

Would allow for clean and flexible way of controlling of bundle's behaviour.
