### ISSUE TITLE
[3.0] Normalizers usage

### ISSUE THREAD

**Issue by tristanbes** [algolia/search-bundle#139]
Hello,

I seen that 3.x uses a new concept to serialize data based on the Symfony serializer which is a great move IMHO.

If I already have a set of normalizer for my objects, BUT i don't want them to be used for Algolia (and use the one I provide instead), is there a way to do this ?

Can I use the `normalizers` key to provide only "whitelisted" normalizers ?

```
    - name: comments
      class: App\Entity\Comment
      normalizers:
        - App\Normalizers\CommentNormalizer
        - Symfony\Component\Serializer\Normalizer\CustomNormalizer
        - Algolia\SearchBundle\Normalizer\SearchableArrayNormalizer
```

Also, in that case I will have 2 normalizer for 1 object `Foo`

How can I ensure that my previous code still uses the `Normalizer` I wrote and not uses the one I wrote for Algolia service ?
