### ISSUE TITLE
[3.0] Import command via indice name

### ISSUE THREAD

**Issue by tristanbes** [algolia/search-bundle#143]
It could be nice to have the `search:import` command to accept name of the indice for DX.

So given this config: 

```yml
 algolia_search:
    indices:
        - name: cv
          class: AppBundle\Entity\Cv
```

When running:
`search:import cv` it works out of the box (or even a list of indices to import)

It's better than to write `search:import AppBundle:Cv` (because `AppBundle:Cv` doesn't even appear in the configuration)

What do you think ?
