### ISSUE TITLE
[3.0] Environement indexing is no longer possible

### ISSUE THREAD

**Issue by tristanbes** [algolia/search-bundle#145]
I was writing the `UPGRADE` guide when I realize it's no longer possible to achieve the per environnement indexing feature.

In the guide I was writing that you need to overwrite the indice name like:
```yml
// config.yml
algolia_search:
    indices:
        - name: posts
          class: App\Entity\Post
```

```yml
// config_dev.yml
algolia_search:
    indices:
        - name: posts_dev
          class: App\Entity\Post
```

But if you do that 2 things will happen:

1. it will create a new `indice` inside algolia with name `posts_dev` and push data inside it which is good.
2. it will still erease/update data to indice `posts` too (and it's **NOT** what we want) 

I think you should do something in the config like:

```yml
// config.yml
algolia_search:
    indices:
        posts: # config key
            name: posts # indice name
            class: App\Entity\Post
```

So we can actually **overwrite it**: 
```yml
// config_dev.yml
algolia_search:
    indices:
        posts:
            name: posts_dev # overwritten indice name
            class: App\Entity\Post
```

If you make this changes, you should then change the content of #143 which should take not the indice name, but the `config key` (in my example: `posts`)

What do you think ?
