### ISSUE TITLE
[3.0] Indexing by name of indice is ignored and index all indices.

### ISSUE THREAD

**Issue by tristanbes** [algolia/search-bundle#183]
Was wondering why it took a long time for my 3k objects. It's because it's ignoring the name of index to index, and it indexes all objects...

`bin/console search:import multigaming`

```yml
algolia_search:
    indices:
        - name: cv
          class: AppBundle\Entity\Cv
        - name: team
          class: AppBundle\Entity\Team
        - name: multigaming
          class: AppBundle\Entity\Multigaming
```

<img width="680" alt="1__ _symfony_console _search_import_multigaming__ssh_" src="https://user-images.githubusercontent.com/346010/34365132-2fb07fa8-ea8d-11e7-840b-fc87394ffebc.png">
