### ISSUE TITLE
First indexing : error "Not enough rights to add an object"

### ISSUE THREAD

**Issue by eved42** [algolia/search-bundle#267]
- Symfony version: 4.1
- Algolia Search Bundle version: 3.3
- Algolia Client Version: ?
- Language Version: ?

### Description
When I tried to do my first indexing with command `php bin/console search:import` I've got the following error : 
![2018-10-16 12_33_23-invite de commandes](https://user-images.githubusercontent.com/12841417/47010642-e3cfee80-d13f-11e8-9043-733263db1927.png)
Note : don't pay attention to the deprecated warning.

**algolia_search.yaml**
```
algolia_search:
    prefix: '%env(APP_ENV)%_'
    indices:
      - name: customers
        class: App\Entity\Customer
        enable_serializer_groups: true
        index_if: isIndexable

      - name: prescribers
        class: App\Entity\Prescriber
        enable_serializer_groups: true
        index_if: isIndexable
```
I added the Groups annotations in my entities and created a public function `isIndexable()` to index only specific customers and prescribers.

### Steps To Reproduce
I have a Symfony 4 simple project. I work locally on a PC with Wampserver. I've just installed your bundle, modified my entities and tried to do the first indexing.

I created an account on algolia.com and put the App Id and the Search-only API Key in the `.env` file.
