### ISSUE TITLE
Index the same entity twice with different indice name

### ISSUE THREAD

**Issue by B-Galati** [algolia/search-bundle#269]
Hello !

- Symfony version: 4.1.6
- Algolia Search Bundle version: 3.3.2
- Algolia Client Version: 1.27.0
- Language Version: 7.2.7

### Description

I was trying to index the same entity twice with 2 indices name.
My goal was to leverage instantsearch.js [sortBySelector](https://community.algolia.com/instantsearch.js/v2/widgets/sortBySelector.html) widget.

So I did something like this:

```
algolia_search:
    indices:
        - name: publication
          class: App\Entity\Publication
          index_if: isPublished
          enable_serializer_groups: true

        - name: publication_sort_by_date_desc
          class: App\Entity\Publication
          index_if: isPublished
          enable_serializer_groups: true
```

It looks like it was working as expected at 1st glance but no.
Only the last declared indice is pushed to Algolia. The others are not updated anymore: no clear, no update, no import, etc.

Is this something that could be interesting to support within the bundle? Am I going to the wrong direction and this feature should be implemented differently?
At the end, if this is a bad idea, an error message to prevent creating such a config could really nice for DX. Perhaps I missed something in the doc.

Cheers and thanks for this awesome bundle :+1:
