### ISSUE TITLE
Command search:clear doesnt consider prefix

### ISSUE THREAD

**Issue by pedrocasado** [algolia/search-bundle#303]
- Symfony version: 3.4.26
- Algolia Search Bundle version: 3.4.0
- Algolia Client Version: 1.28.0
- Language Version: php7.2

### Description

The search:clear command doesnt consider prefix on index name.

### Steps To Reproduce

- Create an index called prod_product
- Create an entity Product
- Setup bundle

```
algolia_search:
    prefix: prod
    indices:
        - name: product
          class: AppBundle\Entity\Product
          enable_serializer_groups: true
```

- Run task

````
$ ./bin/console search:clear --env=prod
```

Result:

```
Index product  couldn't be cleared
Done!
````

Index name should consider prefix and be prod_product
