### ISSUE TITLE
Class 'Algolia\SearchBundle\Document\Aggregator' does not exist 

### ISSUE THREAD

**Issue by ostrolucky** [algolia/search-bundle#312]
Repening https://github.com/algolia/search-bundle/issues/304 as this is still an issue, hopefully I will provide more info

- Symfony version: 3.4.32
- Algolia Search Bundle version: 4.0.0-alpha2
- Algolia Client Version: 2.4.0
- Language Version: 7.3.10
- doctrine-odm-bundle Version: 3.6.1

This happens when using `doctrine_mongodb.document_managers.default.auto_mapping: true` setting. I think this will keep happening while bundle defines *mongodb.xml file, but no `\Document` namespace.

Here is the cause of this behaviour being triggered https://github.com/symfony/symfony/blob/c5024bdbd08550307321ed67a658c8442f65a536/src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php#L164

**Comment by chloelbn** [comment]
Hello @ostrolucky 

Thanks a lot for your detailed feedback.
With doctrine-odm-bundle you have the possibility to alias namespaces. With that in mind, it can be a workaround to alias our `SearchBundle\Entity` namespace to `SearchBundle\Document`, like this:
```
doctrine_mongodb:
    // ...
    document_managers:
        default:
            auto_mapping: true
            mappings:
                AlgoliaSearchBundle:
                    prefix: 'Algolia\SearchBundle\Entity'
                    alias: 'Algolia\SearchBundle\Document'
```

Tell me if it could work for you.
@alcaeus, could you give us your feedback about that solution as well?

Thanks a lot!
