### ISSUE TITLE
Proxy objects indexed when used with Aggregator

### ISSUE THREAD

**Issue by PierrickMartos** [algolia/search-bundle#339]
Hi,

- Symfony version: 3.4.39
- Algolia Search Bundle version: 3.4.0
- Algolia Client Version: 1.28.0
- Language Version: 7.3.13

### Description

I use the aggregator since a few days and i've found an issue during objects index. For some objects, can't find out why and specially **when**, i got two items uploaded, one with the right class name and one with the doctrine proxy, e.g of an ObjectId: `Proxies\__CG__\SAM\AddressBookBundle\Entity\ContactMerged::22783`

Here is a screenshot from my algolia indice with the two objects (i've done an indice clear before i runned : bin/console search:import)

![image](https://user-images.githubusercontent.com/1785711/78111824-8e53d400-73fd-11ea-8a97-c81ce69cf079.png)

Here is the error when doing search:
`Uncaught PHP Exception Algolia\SearchBundle\Exception\EntityNotFoundInObjectID: "Entity class from ObjectID Proxies\__CG__\SAM\AddressBookBundle\Entity\ContactMerged::22783 not found." at /var/app/current/vendor/algolia/search-bundle/src/Entity/Aggregator.php line 83`

### Steps To Reproduce

My aggregator class:

```php
<?php

namespace SAM\CommonBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Algolia\SearchBundle\Entity\Aggregator;
use AppBundle\Entity\Company;
use AppBundle\Entity\DealFlow;
use SAM\AddressBookBundle\Entity\ContactMerged;
use SAM\DealFlowBundle\Repository\DealFlowRepositoryInterface;

/**
 * @ORM\Entity
 */
class SearchItem extends Aggregator
{
    /**
     * @return bool
     */
    public function isPublished()
    {
        return !property_exists($this->entity, 'isntSoftDeleted') || true === $this->entity->isntSoftDeleted();
    }

    /**
     * @return string[]
     */
    public static function getEntities()
    {
        $entities = [
            Company::class,
            ContactMerged::class,
        ];

        if (interface_exists(DealFlowRepositoryInterface::class)) {
            $entities[] = DealFlow::class;
        }

        ....

        return $entities;
    }
}
```

My conf:
```
algolia_search:
    nbResults: 20
    prefix: '%env(ALGOLIA_SEARCH_PREFIX)%'
    indices:
        ...

        - name: search_item
          class: SAM\CommonBundle\Entity\SearchItem
          enable_serializer_groups: false
          index_if: isPublished

    # Doctrine events are handle by our SearchIndexerSubscriber (in SAMCommonBundle)
    doctrineSubscribedEvents: []
```
